.gitignore
maiar-starter/package.json
maiar-starter/src/index.ts
packages/core/src/memory/service.ts
packages/core/src/runtime/index.ts
packages/plugin-x/README.md
packages/plugin-x/package.json
packages/plugin-x/src/index.ts
packages/plugin-x/src/plugin.ts
packages/plugin-x/src/templates.ts
packages/plugin-x/src/types.ts
packages/plugin-x/tsconfig.json
pnpm-lock.yaml

This PR introduces the starter configuration for the X plugin.
The default trigger checks mentions every minute and replies to all posts that don't have a response from the agent.
We implement two major actions `post_tweet` and `send_tweet`.
The `post_tweet` action is invoked by telling the agent to post a tweet from another platform such as the express server.
The `send_tweet` action is invoked as a reply to a post on X. We invoke this in our mention's trigger so that the agent runs this executor to respond.
USE THIS PLUGIN AT YOUR OWN RISK. THIS IS NOT AN OFFICIALLY SUPPORTED X API AND YOU ARE RISKING AN ACCOUNT BAN BY USING THIS. WAIT FOR OFFICIAL API SUPPORT IF THIS CONCERNS YOU.
NA
Reference `maiar-starter` code for setting up X client. Mention your agent on X and note the response. …

feat: stand up x plugin

---

maiar-starter/character.xml
maiar-starter/package.json
maiar-starter/src/index.ts
packages/plugin-character/README.md
packages/plugin-character/package.json
packages/plugin-character/src/index.ts
packages/plugin-character/src/plugin.ts
packages/plugin-character/src/types.ts
packages/plugin-character/tsconfig.json
pnpm-lock.yaml

Created a basic character plugin so that you can influence how the agent behaves and responds in user-facing outputs.
When the character plugin is present, the agent is directed to inject that character information at the start of every pipeline.
This is a really simple implementation on purpose. It demonstrates plugin composability. This plugin can be the starting point for building out a more dynamic character configuration that adapts to messages, new data, and previous operations.
NA
Example character file in `maiar-starter` called `character.xml` supplies the test character. You can structure this file however you like. We are just feeding a string into the character context.
```
maiar-ai 0xpbit > curl -X POST http://localhost:3000/message \
-H "Content-Type: application/json" \
-d …
```

feat: plugin for character configuration

---

maiar-starter/package.json
maiar-starter/src/index.ts
packages/plugin-search/README.md
packages/plugin-search/package.json
packages/plugin-search/src/index.ts
packages/plugin-search/src/perplexity.ts
packages/plugin-search/src/plugin.ts
packages/plugin-search/src/templates.ts
packages/plugin-search/src/types.ts
packages/plugin-search/tsconfig.json
pnpm-lock.yaml

Adds a search plugin leveraging perplexity to get real-time up to date information.
NA
Request real-time information from the agent while `plugin-search` is registered in the agent configuration.
```
maiar-ai 0xpbit > curl -X POST http://localhost:3000/message \
-H "Content-Type: application/json" \
-d '{"message": "What is the current price of solana?", "user": "test-user"}'
"The current price of Solana (SOL) varies slightly across different platforms. As of the latest updates, it is approximately between $195 and $200. For example, it's $197.12 on Binance, $195.66 on Blockworks, $196.47 on KuCoin, $198.73 on Coinbase, and $198.54 on Crypto.com."%   
```

feat: perplexity search plugin

---

.github/workflows/release.yaml
maiar-starter/package.json
package.json
pnpm-lock.yaml
turbo.json
website/package.json

- Separate build command for `maiar-starter` / `packages/*` / `website` to make it granular for DX. 
- Re-configured `turbo.json` to declare correct dependencies so caching is more effective. 
- Cleaned unused `turbo.json` commands i.e. `test`
- Cleaned unnecessary dependencies in `maiar-starter`
- Update `release.yaml` to use updated build command for packages `pnpm build`
- `build` command was building everything i.e. `maiar-starter` / `packages/*` / `website` - needed to make the command more granular so developers can build specific areas they are working on
```
rm -rf .turbo ./**/.turbo
rm -rf ./**/dist
pnpm build
pnpm build:starter
```
```
$ pnpm build
> turbo run build --filter=./packages/*
• Packages in scope: @maiar-ai/core, @maiar-ai/memory-filesystem, @maiar-ai/memory-sqlite, …
```

♻️ refactor(config): Separate build command for maiar-starter/packages/website

---

.gitignore
README.md
maiar-starter/package.json
package.json
pnpm-lock.yaml
website/docs/contributing-guide.md
website/docusaurus.config.ts
website/sidebar-docs.ts

- Provides a seamless DX against the Maiar AI core packages from a project using Maiar core packages as dependencies
- Documents the DX again the Maiar AI core packages in the README.md and docs website
The development workflow is orchestrated through two key components:
1. Root monorepo build watcher
2. Starter project development server
**Root Monorepo Build Watcher**
```json:package.json
"dev": "rm -f .build-complete && pnpm run build && touch .build-complete && chokidar 'packages/**/*.ts' --ignore 'packages/**/dist/**' -c 'rm -f .build-complete && pnpm run build && touch .build-complete'"
```
This command:
1. Removes any existing `.build-complete` marker
2. Performs initial build of all packages
3. Creates `.build-complete` marker to signal build completion
4. Watches for changes in …

chore(setup): 🔧📝 implement/document seamless development workflow

---

maiar-starter/package.json
maiar-starter/src/index.ts
packages/plugin-x/src/plugin.ts
packages/plugin-x/src/templates.ts
pnpm-lock.yaml

The logging syntax that is in the current plugin-x is incorrect and it produces invalid logs that do not show the stack trace:
```
[2025-02-16 20:38:35.936 -0600] ERROR: plugin:x: Error processing tweets from generator:
component: "plugin:x"
[2025-02-16 20:38:35.936 -0600] ERROR: plugin:x: Error in checkMentions:
component: "plugin:x"
[2025-02-16 20:38:35.936 -0600] ERROR: plugin:x: Stack trace:
component: "plugin:x"
[2025-02-16 20:38:35.936 -0600] ERROR: plugin:x: Full error details:
component: "plugin:x"
[2025-02-16 20:38:35.936 -0600] ERROR: plugin:x: Error in checkMentions:
component: "plugin:x"
[2025-02-16 20:38:35.936 -0600] ERROR: plugin:x: Stack trace:
component: "plugin:x"
[2025-02-16 20:38:35.936 -0600] ERROR: plugin:x: Full error:
component: "plugin:x"
```
This PR fixes the …

fix: correct error logging syntax in plugin-x

---

website/docusaurus.config.ts
website/src/css/plugins.module.css
website/src/pages/index.tsx
website/src/pages/plugins.tsx

- 🧩 added plugins page to docs website
- 🔧 added plugins link to navbar
To support community plugins! 🥳 
```
cd website
pnpm start
```
```
pnpm build:website
pnpm serve
```

docs(website): 🧩 add plugins page to docs website

---

.commitlintrc.ts

adds two items to the commitlint some. 
NA
added plugin-search and plugin-x to the scope
NA

chore(config): added new plugins to commitlint scope

---

packages/plugin-terminal/README.md

Add documentation that was missed in #30 
#26 
N/A

docs(plugin-terminal): add configuration, plugin information and usage section to README

---

website/src/pages/index.tsx

css causing CA to be all lowercase
na
NA

fix: update landing page ca

---

website/docusaurus.config.ts

Maiar Hackathon 2025 Announcement Bar 🥳 
Maiar Hackathon 2025 Announcement not in Announcement Bar or on website in general
```
cd website
pnpm build:website
pnpm serve
```
```
cd website
pnpm start
```

docs(website): 💻 hackathon 2025 announcement

---

website/docs/getting-started.md

starter example was wrong since we changed plugin express
incorrect syntax in getting started code 
Copy and paste in your environment to run

docs: update starter code example

---

.github/scripts/bounty/calculate-bounty.js
.github/scripts/bounty/extract-issues.js
.github/scripts/bounty/extract-wallet.js
.github/scripts/bounty/filter-bounty-issues.js
.github/scripts/bounty/label-issues-paid.js
.github/scripts/bounty/thank-contributor-tx.js
.github/scripts/lib/github.js
.github/scripts/thank-you/thank-contributor.js
.github/workflows/bounty.yaml
.github/workflows/thank-you.yaml

- 💰 Add PR Payment GHA Workflow to facilitate the $MAIAR Bounty Program
- 🎉 Thank Contributors when PR is merged by submitting a comment on their PR
💰 $MAIAR Initial Roadmap Phase 4 - Bounty Program for contributors
1. Create an issue
2. Label the issue with `bounty` label (Can only be done by a CODEOWNER`
3. CODEOWNER comments on the issue with the format `bounty: <amount> $MAIAR`
4. Contributor makes a PR
5. CODEOWNER comments on contributor's PR with the `bounty` labeled issue(s) the PR closes/fixes/resolves (i.e. "Closes/Fixes/Resolves #<issue-number>"
6. Contributor comments on the PR with their solana wallet address in the format `solana:<wallet-address>`
7. CODEOWNER approves + rebases and merges contributor's PR
8. The steps above will kickoff the `bounty.yaml` GHA workflow that …

ci: 💰 add bounty program

---

.github/CONTRIBUTING.md
README.md
website/docs/01-building-plugins/01-philosophy.md
website/docs/bounty-program.md
website/docs/contributing-guide.md
website/docs/index.md
website/docusaurus.config.ts
website/sidebar-docs.ts

Adds bounty program info
NA
NA

docs: bounty program

---

maiar-starter/src/index.ts
packages/model-ollama/src/deepseek.ts
packages/model-ollama/src/ollama.ts
packages/model-openai/src/openai.ts
website/docs/01-building-plugins/02-executors.md
website/docs/01-building-plugins/03-triggers.md
website/docs/01-building-plugins/index.md
website/docs/02-model-providers/01-overview.md
website/docs/02-model-providers/02-capabilities.md
website/docs/02-model-providers/index.md
website/docs/03-memory-providers/01-overview.md
website/docs/03-memory-providers/index.md
website/docs/04-monitor-providers/01-overview.md
website/docs/04-monitor-providers/02-console-monitor.md
website/docs/04-monitor-providers/03-websocket-monitor.md
website/docs/04-monitor-providers/04-custom-monitors.md
website/docs/04-monitor-providers/05-maiar-client.md
website/docs/04-monitor-providers/index.md
website/docs/05-core-utilities/createEvent.md
website/docs/05-core-utilities/getObject.md
website/docs/05-core-utilities/index.md
website/docs/05-core-utilities/runtime.md
website/docs/bounty-program.md
website/docs/contributing-guide.md
website/docs/getting-started.md
website/sidebar-docs.ts

Made a small change to use Enums in the openai model provider instead of using raw strings to get some more compile time checking. Also introduced detailed capability documentation to maiar.dev website.

chore: docs additions and small enum rework for openai

---

maiar-client/src/components/EventFilter.tsx
maiar-client/src/components/Events.tsx
maiar-client/src/components/GridLayout.tsx
maiar-starter/src/index.ts

adds event filters so it's easy to search the even type you are looking for
NA
make events. search for their name.

chore: add event filtering

---

maiar-client/src/components/GridLayout.tsx
maiar-starter/src/index.ts
packages/core/src/index.ts
packages/core/src/models/base.ts
packages/core/src/models/index.ts
packages/core/src/models/service.ts
packages/core/src/models/types.ts
packages/core/src/runtime/index.ts
packages/core/src/runtime/types.ts
packages/model-openai/src/index.ts
packages/model-openai/src/openai.ts
packages/model-openai/src/types.ts
packages/plugin-image/src/plugin.ts
packages/plugin-image/src/types.ts
packages/plugin-image/tsconfig.json
packages/plugin-text/src/plugin.ts
packages/plugin-text/src/types.ts
website/docs/02-model-providers/02-capabilities.md

Improves the type safety of the capabilities system by enforcing proper input/output type structure and preventing usage of undefined capabilities. This change makes the type system more robust by adding a module augmentation pattern. now plugin developers and model developers explicitly declare the capabilities they will be consuming/producing respectively.
resolves #53 
```diff
// packages/core/src/models/types.ts
/**
* This is the base interface for all capabilities.
* Model providers and plugins will extend ICapabilities with the input and output types
*/
export interface BaseCapability {
input: unknown;
output: unknown;
}
/**
* This is the base interface for all capabilities.
* Model providers and plugins can extend this interface
* to add their own capabilities.
*/
// …
```

feat: capability module declare compile time type checking

---

packages/plugin-discord/src/plugin.ts

creates oauth login URL and publishes it over the monitor
run

chore: add oauth invite URL on discord plugin init

---

website/docs/04-monitor-providers/05-maiar-client.md

Updates `maiar-client` to correct path in docs

docs: fix maiar-client path

---

packages/core/src/lib/winston/transports/websocket.ts
packages/core/src/runtime/index.ts
packages/core/src/runtime/managers/server.ts
packages/core/src/runtime/providers/plugin.types.ts
packages/plugin-text/package.json
packages/plugin-text/src/plugin.ts
pnpm-lock.yaml

This PR resolves several critical issues affecting production deployments on DigitalOcean App Platform. The changes ensure WebSocket connections work properly behind proxies, improve routing handling, and provide better middleware control for plugin routes.
resolves #92 
fixes #91 
1. **WebSocket Fix**:
- Deploy to DigitalOcean App Platform
- Connect to the /monitor WebSocket endpoint from a client
- Verify logs are streaming properly without connection errors
2. **Custom Middleware**:
- Create a plugin with a route that receives non-JSON data
- Specify express.text() middleware for the route
- Verify the route correctly receives and processes the text payload
3. **Express Routing**:
- Deploy to DigitalOcean
- Verify the health check endpoint at the root path (GET /) returns a 200 status …

feat(core): default route, custom middleware, websocket upgrade

---

.commitlintrc.ts
.github/workflows/ci.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
nx.json
package.json

feat(nx-cloud): setup nx cloud workspace
This commit sets up Nx Cloud for your Nx workspace, enabling distributed caching and the Nx Cloud GitHub integration for fast CI and improved developer experience.
You can access your Nx Cloud workspace by going to
https://cloud.nx.app/orgs/680680a3fd4eb5799867a987/workspaces/680680b4fd4eb5799867a98a
**Note:** This commit attempts to maintain formatting of the nx.json file, however you may need to correct formatting by running an nx format command and committing the changes.

ci(nx): ☁️ set up nx cloud workspace

---

apps/starter/src/index.ts
packages/model-openai/src/types.ts

adds gpt 4.1 to model-openai
https://x.com/0xPBIT/status/1912264994965569702

feat(model-openai): add new GPT-4.1 models to text capabilities

---

.commitlintrc.ts
apps/starter/package.json
apps/starter/src/index.ts
packages/plugin-codex/package.json
packages/plugin-codex/src/index.ts
packages/plugin-codex/src/plugin.ts
packages/plugin-codex/src/templates.ts
packages/plugin-codex/src/types.ts
packages/plugin-codex/tsconfig.json
pnpm-lock.yaml

This pull request introduces the `Codex Plugin` to the MAIAR AI Agent ecosystem, enhancing the capabilities of MAIAR by integrating with the powerful [Codex CLI by OpenAI](https://github.com/openai/codex). This plugin enables seamless interaction with Codex, allowing users to leverage advanced code generation and automation features directly within the MAIAR environment.
- **Codex CLI Integration**: The plugin interfaces with the Codex CLI, enabling MAIAR to execute Codex commands for code generation, editing, and other development tasks.
- **Automated Code Generation**: Users can request the creation of applications or components (e.g., a fancy todo-list app) with specific requirements, and Codex will generate the necessary code automatically.
- **Customizable Command Execution**: The …

feat(plugin-codex): plugin codex standup

---

CHANGELOG.md

- Updates `CHANGELOG.md` to use Nx style release notes
We are not using Nx style release notes
N/A

docs(release): 📝 update changelog releases to use Nx style release notes

---

README.md

- Add contributors to `README.md` using https://contrib.rocks
- Acknowledge Contributors in `README.md`
Checkout `README.md`

docs: 📝 add contributors to README.md

---

README.md

- Update quickstart section in `README.md`
- Quickstart section in `README.md` is outdated
Checkout `README.md`

docs: 📝 update quickstart section in README.md

---

README.md

- Add Star History in `README.md` using https://api.star-history.com
- Showcase Github Stars History
Checkout `README.md`

docs: 📝 add star history to README.md

---

.github/workflows/ci.yaml
.github/workflows/pre-release.yaml
.github/workflows/release.yaml

- added explicit permissions to workflows ci/pre-release/release
CodeQL Scanning Issues
Workflow Results with explicit permissions on forked repo:
- CI Workflow - https://github.com/ktn1234/maiar-ai/actions/runs/14698117139
- Github Release - https://github.com/ktn1234/maiar-ai/actions/runs/14698060157 (If it works on release, it will work on pre-release)

ci(ci,cd): 🛂 added explicit permissions to workflows ci/pre-release/release

---

.commitlintrc.ts
.github/CONTRIBUTING.md

- Update contributing guide commit history, conventional commits, and pull requests section
- Outdated CONTRIBUTING.md
Check .github/CONTRIBUTING.md

docs: 📝update contributing guide commit history, conventional commits, and pull requests section

---

.github/workflows/ci.yaml
nx.json
package.json
packages/core/package.json
packages/core/src/index.test.ts
packages/memory-postgres/package.json
packages/memory-sqlite/package.json
packages/model-ollama/package.json
packages/model-openai/package.json
packages/plugin-character/package.json
packages/plugin-codex/package.json
packages/plugin-discord/package.json
packages/plugin-image/package.json
packages/plugin-mcp/package.json
packages/plugin-search/package.json
packages/plugin-telegram/package.json
packages/plugin-terminal/package.json
packages/plugin-text/package.json
packages/plugin-time/package.json
packages/plugin-websocket/package.json
packages/plugin-x/package.json
pnpm-lock.yaml
vitest.config.ts

🧪 Standup testing framework vitest for maiar-air repo
❌ No testing in maiar-ai repo
```
pnpm test
```
```
pnpm test
pnpm test:watch
pnpm test:ui
```

test(config): 🧪🔧 standup vitest

---

packages/core/src/runtime/managers/prompts/pipeline_generate.liquid
packages/core/src/runtime/pipeline/processor.ts
packages/core/src/runtime/pipeline/types.ts

pipeline failed to create due to misnamed variable

fix(core): pipeline creation step

---

apps/website/src/pages/index.tsx

uses `will-change` to optimize landing page

docs: optimize landing page

---

README.md

updates the readme to use the new maiar CLI for quickstart

docs: update new quickstart guide in readme

---

apps/client/src/components/AgentStatus.tsx
apps/client/src/types/monitorSpec.ts
apps/starter/src/index.ts
packages/core/src/monitor/events.ts
packages/core/src/runtime/index.ts
packages/core/src/runtime/pipeline/scheduler.ts

This PR implements concurrent task execution in the scheduler system. Previously, the scheduler processed agent tasks sequentially, which could create bottlenecks when handling multiple simultaneous triggers or long-running operations. This enhancement allows the scheduler to process multiple tasks concurrently up to a configurable limit (default: 4 concurrent tasks).
Most of the changes related to concurrency are taking place inside the scheduler loop.
resolves #180
1. **Configure concurrency settings** (optional):
```typescript
// In your runtime initialization
const runtime = await Runtime.init({
concurrency: {
maxTasks: 6 // Process up to 6 tasks concurrently (default: 4)
}
});
```
2. **Start the application**:
```bash
pnpm dev
```
3. **Verify concurrent execution**:
- Open the …

feat(core): concurrent task processing
