.github/workflows/release.yaml

If you enable branch protection rules with `Require a pull request before merging > Allow specified actors to bypass required pull requests`, you can add a Github App to be authorized to push API doc updates.
Created maiar-intern Github App, installed it on UraniumCorporation org to allow access to maiar-ai repo, added secrets `APP_ID` and `APP_PRIVATE_KEY`, and install it on the `generate-docs` job to checkout the code under the bot with permissions to commit/push API doc updates
Currently, it is using the default `github-actions[bot]` to commit/push API doc changes and if you enable the branch protection rule `Require a pull request before merging`, this bot cannot be added as an `Allowed specified actors to bypass required pull requests` so the workflow job will fail on this job i.e. …

🐛🤖 cd(bug): update api doc changes using installed github apps

---

.github/CONTRIBUTING.md
website/docs/getting-started.md
website/docs/index.md
website/docusaurus.config.ts

Updates all discord references in `CONTRIBUTING.md` docs and website docs to reference Maiar's discord branded link 
Discord references in `CONTRIBUTING.md` docs and website docs reference old discord non-branded link
```sh
cd website
pnpm start
```
Hover over discord link in:
- http://localhost:3000/docs
- http://localhost:3000/docs/getting-started
- Footer
They all point to https://discord.gg/maiar

📝🔗 docs(website,other): update discord link to branded link

---

website/docusaurus.config.ts

Added whitepapers link (https://maiar.dev/maiar.pdf) in the docs website in the NavBar + Footer since it was missing
Whitepapers link missing in docs website
```sh
cd website
pnpm start # or pnpm build && pnpm serve
```
- Go to http://localhost:3000/docs or any docs page
- Hover over Whitepaper link on the NavBar on the righthand side and observe it points to https://maiar.dev/maiar.pdf
- Hover over Whitepaper link on the Footer on the righthand side and observe it points to https://maiar.dev/maiar.pdf

📝🔗 docs(website): add whitepaper link to navbar/footer

---

.github/workflows/release.yaml
package.json
packages/core/package.json
packages/memory-filesystem/package.json
packages/memory-sqlite/package.json
packages/model-ollama/package.json
packages/model-openai/package.json
packages/plugin-character/package.json
packages/plugin-express/package.json
packages/plugin-image/package.json
packages/plugin-search/package.json
packages/plugin-telegram/package.json
packages/plugin-terminal/package.json
packages/plugin-text/package.json
packages/plugin-time/package.json
packages/plugin-websocket/package.json
packages/plugin-x/package.json

Runs `prepublishOnly` [lifecycle script](https://dyte.io/blog/package-json-scripts/#:~:text=lifecycle%20scripts%20are%20a%20set,json%20file%20of%20a%20Node.) before publishing to npm by adding a `prepublishOnly` script to all packages that builds the package, and removes `---ignore-scripts` flag using `lerna publish` command so it will run npm [lifecycle scripts](https://dyte.io/blog/package-json-scripts/#:~:text=lifecycle%20scripts%20are%20a%20set,json%20file%20of%20a%20Node.) `prepublishOnly` script for all packages that will be published before publishing it
The `release.yaml` workflow was using `lerna publish` with `--ignore-scripts` flag that did not run the lifecycle scripts and on top of that, important lifecycle scripts such as `prepublishOnly` command that builds the package …

🏗️⚡️ cd(fix): Run prepublishOnly lifecycle script before publishing to npm

---

packages/core/src/models/base.ts
packages/core/src/models/service.ts
packages/core/src/runtime/index.ts
packages/model-ollama/src/deepseek.ts
packages/model-ollama/src/index.ts
packages/model-ollama/src/ollama.ts
packages/model-openai/src/openai.ts

This indirectly solves the case when a Model is misconfigured. The current implementation:
* Adds `checkHealth()` function to the interface
* Implements the function in all the current models (openAI, ollama, deepseek)
* Outputs the current list of existing models for both Ollama and deepseek when the config of the plugin is incorrect, etc.
* For details on how to run Ollama: https://gist.github.com/marcellodesales/7be67c13d6799628dcb6954155fbd765
> [!CAUTION]
> * When an OpenAI token has no credits and the server is unable to send any requests 
> * The new log statement would show users this is a healthcheck error and they should follow the possible solutions
> ```
> [2025-02-15 18:58:40.425 -0800] ERROR: model:openai: Model openai health check failed
> ```
For this reason, this ticket …

bug: 🐛 verify models healthcheck before bootstraping the server

---

.commitlintrc.ts

Disable git commit header/subject/body/footer max length in `commitlint` config
Git commit messages blocked by a `commitlint` max length rule during pre-commit hooks for the header/subject/body/footer for chars exceeding 100 (`commitlint` default rule)
```sh
git commit --allow-empty  -m "chore: <subject longer than 100 chars>
<description longer than 100 chars>
<footer longer than 100 chars>"
```
```sh
git commit --allow-empty -m "test: 1234567890qwertyuiopasdfghjklzzxcvbnm1234567890qwertyuiopasdfghjklzzxcvbnm1234567890qwertyuiopasdfghjklzzxcvbnm
1234567890qwertyuiopasdfghjklzzxcvbnm 1234567890qwertyuiopasdfghjklzzxcvbnm 1234567890qwertyuiopasdfghjklzzxcvbnm
1234567890qwertyuiopasdfghjklzzxcvbnm 1234567890qwertyuiopasdfghjklzzxcvbnm 1234567890qwertyuiopasdfghjklzzxcvbnm"
> …
```

chore(setup): 🔧 disable git commit header/subject/body/footer max length

---

.github/workflows/release.yaml

Install `maiar-intern` GH App on the package-release job that has permissions to commit/push to github
package-release job could not commit/push to github due to permission error - https://github.com/UraniumCorporation/maiar-ai/actions/runs/13365650585/job/37322791960
Workflow Run demonstrating this is working - https://github.com/k3v-d3v/maiar-ai/actions/runs/13344782861/job/37273898721
Workflow File for the Workflow Run - https://github.com/k3v-d3v/maiar-ai/actions/runs/13344782861/workflow

cd(bug): 🐛⚙️ install maiar-intern gh app in package-release job for git permissions

---

maiar-starter/package.json
maiar-starter/src/app.ts
maiar-starter/src/index.ts
packages/plugin-express/src/plugin.ts
packages/plugin-express/src/types.ts
pnpm-lock.yaml

This expands the express plugin to allow users to create custom routing and path handling logic.
- Mount the plugin instance onto `req.plugin`
- Expand ExpressConfig to include ExpressRoute[]
- Allow users to specify routes using {path: string, method: string, handler: function}
- Mount all user specified routes onto the app instance
Use cases for this would be if a user wanted their `/message` endpoint to  be an authenticated route, they wouldn't need to make any changes in the plugin. Instead they could simply write the auth middleware logic in their app as they would in a normal development context.
```
function checkAuthentication(req, res, next) {
if (!validateAuthHeader(req.headers.authorization) {
return next(new Error('invalid auth'));
}
next()
}
const router = Router();
// …
```

feat: Decouple express routers from express plugin

---

.github/workflows/release.yaml

🐛🔧 Add lerna version flag `--force-publish` to make it so all packages (whether it has changes or not) will bump the SemVer version determined by the conventional commit within the merge
📝 Miscellaneous:
- 🔧 No API doc changes should not error out and gracefully exit
In the package release for v0.6.1, the pipeline determined a patch release was needed but did not bump other packages and only the one that had file changes, however, we need them all to bump as a release train to ensure compatibility for core and official supported plugins
`--force-publish` flag description - https://github.com/lerna/lerna/blob/main/libs/commands/version/README.md#--force-publish
```
When run with this flag, lerna version will force publish the specified packages (comma-separated) or all packages using *. …
```

cd(fix): 🐛🔧 add lerna version flag to ensure a release train

---

maiar-starter/src/index.ts
packages/plugin-x/README.md
packages/plugin-x/src/plugin.ts
packages/plugin-x/src/types.ts

Some simple configuration items have been abstracted up to the plugin config to give the plugin consumers some control over mentions polling and login behavior
NA
You can change the `checkMentions` polling rate.

feat: plugin-x abstract more settings to plugin config

---

.gitignore
README.md
maiar-starter/package.json
package.json
restart.js
website/docs/contributing-guide.md

Currently hot reload fails on all Debian based systems as the `pkill` process is handled differently between operating systems. There is also an issue that prevents projects from rebuilding when the top level packages are rebuilt. This issue is caused by `chokidar` not watching files after they are deleted.
- Do not remove the `.build-complete` file when rebuilding core packages and plugins, instead modify it with the current timestamp
- Instead of using `pkill -f "node dist/index.js"` we save the PID of the process in a `.pid` file at the project level, and when we call a node process to send a SIGTERM signal to that PID, start the project again and store the new PID
- Restart script handles SIGINT signals so that no orphaned processes are left running if the user exits `pnpm dev` with …

bug: cross platform hot reload

---

maiar-starter/package.json
maiar-starter/src/index.ts
packages/plugin-terminal/package.json
packages/plugin-terminal/src/index.ts
packages/plugin-terminal/src/plugin.ts
packages/plugin-terminal/src/scripts/chat.ts
packages/plugin-terminal/src/types.ts
packages/plugin-terminal/tsconfig.json
packages/plugin-terminal/tsup.config.ts
pnpm-lock.yaml

The current `chat.ts` script in the `plugin-terminal` package is not built and included in the npm package. It is also hardcoded with values that a user would want to configure. This PR solve the following issues.
- Chat script is not built along with the rest of the plugin
- `pnpm` script included to easily launch chat session
- Refactored `chat.ts` that is configurable via the plugin terminal setup
Closes #26 
**Terminal 1**
```bash
pnpm dev
```
**Terminal 2**
```bash
cd maiar-starter
pnpm dev
```
**Terminal 3**
```bash
pnpm maiar-chat
```

feat(plugin-terminal): make chat script generic

---

website/src/css/plugins.module.css
website/src/pages/index.tsx
website/src/pages/plugins.tsx

- 🧩 add register plugin button in the /plugins page
- 🐛 fixes home page box being too wide for screen size by using word-break
No link to plugin-registry on docs website in official/community plugins listing page
```
cd website
pnpm start
```
```
pnpm build:website
pnpm serve
```

docs(website): 🧩 add register plugin button

---

maiar-starter/package.json
maiar-starter/src/bot.ts
maiar-starter/src/index.ts
packages/plugin-telegram/README.md
packages/plugin-telegram/package.json
packages/plugin-telegram/src/plugin.ts
packages/plugin-telegram/src/types.ts
pnpm-lock.yaml

This expands the telegram plugin to allow users to create custom telegraf composers.
The key here is that a user can write custom logic for handling commands and everything else on a `Composer`
- Addition of composer into the `TelegramPluginConfig`
- Inject the `TelegramPlugin::this` into the `Telegraf::Context` 
- Mount the user supplied composer onto `this.bot.on`
Use cases:
A user would likely want to be able to specify their own middlewares and/or custom logic for maintaining state/session/context window. To be agnostic of the implementation details we move the plugin to accept handlers instead of hard coding the handlers in the plugin itself.
- Allow users to specify their own custom response handlers (ie `sendMessage(..., {parse_mode: 'HTML'}). This way information could be added to …

feat: make plugin-telegram composable by accepting bot handlers

---

.commitlintrc.ts
.github/workflows/bounty.yaml
.github/workflows/thank-you.yaml
website/src/pages/plugins.tsx

1. 🐛 GHA Fix - For both the `bounty.yaml` and `thank-you.yaml` GHA workflow, download `pnpm` globally first with `npm` then use `pnpm` to download dependencies
2. 🐛 monitor plugin display fix - Loop packages dir and parse anything that starts with `monitor-` to display those plugins on the docs website
1. GHA Workflow for `bounty.yaml` and `thank-you.yaml` was failing during the `📦 Install Dependencies` step since it was downloading dependencies using `npm` instead of `pnpm` which is what the monorepo uses
2. monitor plugins are not displaying on the docusaurus website page
For GHA workflow:
1. create a new workflow called .github/test.yaml
2. add a step that installs dependencies using:
```
- name: 📦 Install dependencies
run: |
npm install -g pnpm
pnpm install --save-exact …
```

ci(bounty,thank-you): 🐛 fix GHA workflow dependency installation for bounty program

---

.github/scripts/bounty/calculate-bounty.js
.github/scripts/bounty/extract-issues.js
.github/scripts/bounty/extract-wallet.js
.github/scripts/bounty/filter-bounty-issues.js
.github/scripts/bounty/label-issues-paid.js
.github/scripts/bounty/thank-contributor-tx.js
.github/scripts/lib/github.js
.github/scripts/thank-you/thank-contributor.js

Convert all imports in `.github/scripts/**/*.js` to use ESM import syntax instead of CommonJS
Bounty Payment and Thank you GHA workflow jobs failing due to the root package.json declaring all JS files to be treated as ESM modules so commonJS imports in the current code do not work when trying to run it with node:
- https://github.com/UraniumCorporation/maiar-ai/actions/runs/13826794345/job/38683132367
- https://github.com/UraniumCorporation/maiar-ai/actions/runs/13826794342/job/38683132318
In the root run `pnpm i -w --save-exact @actions/github@6.0.0`
Then run `node .github/scripts/bounty/*.js` or `node .github/scripts/thank-you/*.js`

ci(bounty,thank-you): 🐛 convert commonjs imports to esm imports

---

.github/workflows/bounty.yaml
.github/workflows/thank-you.yaml

Adds explicit permissions on the GHA workflow `issues: write` and `pull-requests: write`
Github actions' default `GITHUB_TOKEN` has read-only permissions unless explicitly overridden. adding `permissions: issues: write` lets it comment on issues/prs.
Read these docs
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes

ci(bounty,thank-you): 🐛 add permissions for GITHUB_TOKEN to write to PRs/issues

---

.github/workflows/bounty.yaml
.github/workflows/thank-you.yaml

Adds explicit permissions on the GHA workflow `content: write`
Github actions' default `GITHUB_TOKEN` has read-only permissions unless explicitly overridden
Read these docs
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes

ci(bounty,thank-you): 🐛 add content write permission for GITHUB_TOKEN to write to PRs/issues

---

.github/workflows/bounty.yaml
.github/workflows/thank-you.yaml

Adds `permissions: write-all` on the GHA workflow `bounty.yaml` and `thank-you.yaml`
Github actions' default `GITHUB_TOKEN` has read-only permissions unless explicitly overridden
Read these docs
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes
Tested in my fork - https://github.com/k3v-d3v/maiar-ai/actions/runs/13830667851/job/38694032070

ci(bounty,thank-you): 🐛 set write permissions to write-all

---

.github/workflows/bounty.yaml
.github/workflows/thank-you.yaml

use the trigger `pull_request_target` in GHA workflows `bounty.yaml` and `thank-you.yaml`
When a contributor forks your repo and raises a Pull Request from that fork the token they get will be read only. So we can’t use it to make comments
- https://jacobtomlinson.dev/posts/2022/commenting-on-pull-requests-with-github-actions/
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
- Tested in k3v-d3v fork
- https://github.com/k3v-d3v/maiar-ai/actions/runs/13844974550/workflow
- https://github.com/k3v-d3v/maiar-ai/actions/runs/13844974550/job/38741244802

ci(bounty,thank-you): 🐛 use pull_request_target trigger

---

maiar-client/src/components/Chat.tsx
maiar-client/src/components/CurrentContextChain.tsx
maiar-client/src/components/CurrentPipeline.tsx
maiar-client/src/components/Events.tsx
maiar-client/src/components/GridLayout.tsx

There was an annoying behavior where new items in the chat, event queue, and context chain elements that would cause the parent scroll view to jump to those elements when new events entered their feeds. This is because I was using `scrollIntoView` which causes the entire parent view to move.
This new change simply scrolls the child element to the latest item on the queue by scrolling all the way down for new events received.
Also fixed the bug that prevented agent status from being resizable.
Use `maiar-chat` and stack event panels top to bottom. In old maiar-chat, your parent scrollview will jump around as new items enter the feed. With this update, the parent view stays in the same place while all the child elements will scroll to the newest item in their containers.

chore: fix scrolling behavior in client + status resize bug

---

packages/core/src/models/base.ts
packages/core/src/monitor/service.ts
packages/core/src/runtime/index.ts
packages/model-openai/src/openai.ts
packages/plugin-x/src/plugin.ts
packages/plugin-x/src/triggers.ts

Rather than attaching the monitors to the runtime and passing them around as a property of the runtime, make them a singleton object instead so that monitors can be used anywhere in the codebase: model providers, memory providers, plugins, or core runtime code
NA
run maiar-starter and maiar-client, observe model lifecycle events in the event view.

feat: make monitor service a singleton

---

.commitlintrc.ts
maiar-starter/package.json
maiar-starter/src/index.ts
packages/memory-postgres/README.md
packages/memory-postgres/package.json
packages/memory-postgres/src/index.ts
packages/memory-postgres/src/provider.ts
packages/memory-postgres/tsconfig.json
pnpm-lock.yaml

Adds a new memory provider `memory-postgres` so the agent can use a remote database like sup abase.
Make a supabase db, add connection string to memory provider config, send message to agent with client

feat: add postgres memory provider

---

maiar-starter/package.json
maiar-starter/src/index.ts
packages/core/src/memory/types.ts
packages/core/src/runtime/index.ts
packages/core/src/types/agent.ts
packages/memory-filesystem/package.json
packages/memory-filesystem/src/plugin.ts
packages/memory-filesystem/src/provider.ts
packages/memory-filesystem/src/templates.ts
packages/memory-filesystem/src/types.ts
packages/memory-postgres/package.json
packages/memory-postgres/src/database.ts
packages/memory-postgres/src/plugin.ts
packages/memory-postgres/src/provider.ts
packages/memory-postgres/src/templates.ts
packages/memory-postgres/src/types.ts
packages/memory-sqlite/package.json
packages/memory-sqlite/src/database.ts
packages/memory-sqlite/src/plugin.ts
packages/memory-sqlite/src/provider.ts
packages/memory-sqlite/src/templates.ts
packages/memory-sqlite/src/types.ts
pnpm-lock.yaml

The best RFC is code
- Created plugins for SQLite, Postgres and FileSystem based memory providers
- Extends `PluginBase` and implements executors that get registered like normal plugins
- Executors for all Memory plugins implement `memory:add_document`, `memory:remove_document` and `memory:query`
- For Postgres and SQLite database singleton classes were created to handle database connections
Closes #43 
Postgres memory provider test
https://github.com/user-attachments/assets/d5d153c1-2bca-4524-8453-b29bc97d610e
SQLite memory provider test
https://github.com/user-attachments/assets/373e4d53-d05c-4e50-9299-043a0b7f4bfc
FileSystem memory provider test
https://github.com/user-attachments/assets/5874991a-bbe2-4e1c-902e-f129d8cd5729

feat(core): extending memory operations with plugin

---

website/docs/bounty-program.md

Adds a small blurb about supported and non supported wallets for our automatic bounty payments.
Issue was first encountered here. This is not a fix, only a way to prevent this issue until this is resolved: https://github.com/UraniumCorporation/maiar-ai/pull/71#issuecomment-2759381129

docs(website): add supported and non-supported wallets warning in bounties docs

---

maiar-starter/src/index.ts
packages/plugin-discord/src/executors.ts
packages/plugin-discord/src/plugin.ts
packages/plugin-discord/src/triggers.ts
packages/plugin-discord/src/types.ts
packages/plugin-x/src/executors.ts
packages/plugin-x/src/plugin.ts
packages/plugin-x/src/triggers.ts
packages/plugin-x/src/types.ts

Deferred Runtime Access in Plugin Executors and Triggers
During plugin initialization, executors and triggers are created before the runtime reference is set on the plugin. This causes runtime-dependent operations to fail when executors or triggers are invoked.
Instead of passing the runtime object directly to executor and trigger factories, we now pass a runtime getter function (`() => this.runtime`). This ensures that:
1. Executors and triggers retrieve the runtime instance at execution time, not at creation time
2. The runtime is always available when needed, regardless of initialization order
3. Third-party plugins can safely access runtime operations like `runtime.operations.getObject`
- Updated `DiscordExecutorFactory` and `DiscordTriggerFactory` to accept a getter function
- …

fix: runtime getter resolves runtime undefined at executor mount

---

nx.json

- Replaces default with a precise list of inputs relevant to the actual build process, including:
- src/** and top-level ts files
- project-specific config files (tsup, vite, tsconfig)
- html and static assets
- docs and metadata files like character.xml
- This change improves cache hit rate while ensuring proper invalidation when relevant inputs change. aAso added minimal input sets for typecheck and lint to keep them efficient and accurate.
- Should reduce CI times and local rebuild noise.
- Docs: https://nx.dev/recipes/running-tasks/configure-inputs
- Previously, the Nx build target used the generic `default` input set, which included all files in the project directory. This was overly broad and could cause unnecessary rebuilds when unrelated files changed.
1. **Clean the cache**: …

chore(config): 🔧 define explicit inputs for build, typecheck, and lint targets to improve task caching

---

.github/workflows/pre-release.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
README.md
nx.json
package.json

Implements a pre-release GHA workflow and standardizes related release infra. Notable changes:
- Adds dedicated pre-release GHA workflow  
- Infers NPM tag from Git tag or workflow input (pre-release, release, publish)  
- Cancels in-progress workflows on same branch for release-related jobs  
- Switches to Nx release subcommands for GitHub release + tagging  
- Refactors Nx config (`release.git` → `release.changelog.git`)  
- Removes unused `--skip-publish` from `nx:release`  npm script
- Minor docs updates + comments for release setup  
This enables smoother prerelease publishing and cleaner job isolation across release flows.
- No dedicated infrastructure for pre-releases. existing release workflows were tightly coupled to stable releases, making it hard to test or publish prerelease …

ci(cd): 👷 add pre-release workflow and automatic tag-based publishing

---

packages/core/src/runtime/index.ts
restart.js

- handle `SIGTERM` in the runtime instance so it gracefully shuts down
- updates `restart.js` to ensure full cleanup of previous processes before starting a new one. It uses `detached: true` to spawn the a new child process in its own process group and terminates it using `process.kill(-pid)`, which kills the entire group, including any subprocesses. This prevents orphaned processes from holding onto ports when rebuilding maiar-starter with new dependencies and is idempotent.
🐛 ports from previous child process weren't being released due to incomplete termination of subprocesses
Shell 1:
```sh
pnpm dev
```
Shell 2:
```sh
cd maiar-starter
pnpm dev
```
Change anything in packages/*
Observe that it rebuilds `maiar-starter` and runs it without any error since it terminates the previous …

fix(core): 🐛 release ports on rebuild by fully terminating prior process group

---

.commitlintrc.ts
apps/starter/package.json
apps/starter/src/index.ts
packages/plugin-mcp/README.md
packages/plugin-mcp/package.json
packages/plugin-mcp/src/index.ts
packages/plugin-mcp/src/plugin.ts
packages/plugin-mcp/src/templates.ts
packages/plugin-mcp/tsconfig.json
pnpm-lock.yaml

This PR introduces **`@maiar-ai/plugin-mcp`**, allowing Maiar to start any [Model Context Protocol (https://github.com/modelcontextprotocol) server at runtime and expose its tools as Maiar executors.  The first consumer is **maiar‑starter**, which now launches the **Puppeteer MCP server** to give the agent browser‑automation powers.
---
|                           | Details |
|---------------------------|---------|
| **Process launch**        | Uses `StdioClientTransport`, spawning `command` + `args` the same way Claude Desktop does. |
| **Tool discovery**        | `listTools()` → each MCP tool becomes a Maiar executor automatically. |
| **Argument generation**   | Converts each tool’s `inputSchema` (JSON‑Schema) → Zod.<br>Calls `runtime.operations.getObject()` with a rich template (full …

feat(plugin-mcp): stand up mcp plugin

---

packages/plugin-mcp/src/plugin.ts

- Adds structured logging and error handling around MCP client lifecycle—specifically during connect and shutdown phases.
- Previously, transport shutdown was silent and error-prone due to loose type assertions and no diagnostics. This improves observability and safety.
```
pnpm build
cd apps/starter
pnpm start
```
Observe useful plugin-mcp logs
```log
...
$MAIAR | 2025-04-25T05:47:48.242Z | INFO | plugin.plugin-mcp | connecting to MCP server... | type=plugin-mcp.init clientName=puppeteer
$MAIAR | 2025-04-25T05:48:12.760Z | INFO | plugin.plugin-mcp | connected to MCP server successfully | type=plugin-mcp.init clientName=puppeteer tools=["puppeteer_navigate","puppeteer_screenshot","puppeteer_click","puppeteer_fill","puppeteer_select","puppeteer_hover","puppeteer_evaluate"]
$MAIAR | …
```

refactor(plugin-mcp): 🔊 improve logging and error handling for client lifecycle

---

packages/plugin-codex/src/plugin.ts

Switches from calling the `codex` binary directly to using `npx codex` for improved portability and to ensure local resolution via `node_modules/.bin` - Drops manual `PATH` extension since `npx` handles that internally.
`plugin-codex` runs the `codex` binary directly, assuming it's accessible via the `PATH`. While this works if the `env` is set up correctly, it's more maintainable to rely on `npx` to resolve it from local `node_modules`
Run the MAIAR Client in a terminal
```
cd apps/client
pnpm dev
```
In another terminal, run:
```
pnpm build
cd apps/starter
pnpm start
```
In the MAIAR Client prompt chat with the agent to:
`Write me cookie clicker in a single html page using Codex - DO NOT ASK MY QUESTIONS ALONG THE WAY`
Observe that codex still works using `npx`

refactor(plugin-codex): ♻️ invoke codex via npx instead of direct binary call

---

nx.json
package.json

- Adds app-specific `dev` and `start` npm scripts for easier local development. Also updates `nx.json` to ensure start runs only after dependent builds via `targetDefaults`. Improves consistency and avoids runtime issues from missing builds.
Developer Experience QoL
Run npm scripts at root dir
- **`start`**  
runs `nx start apps/starter --verbose` — main entrypoint for starting the `starter` app.
- **`dev:client`**  
changes into `apps/client` and runs its local dev server via `pnpm run dev`.
- **`dev:starter`**  
same as above but for `apps/starter`.
- **`dev:website`**  
enters `apps/website` and runs `pnpm run start` — differs slightly from the others, using a custom `start` process instead of `dev`.

chore(nx,config): 🔧 add custom dev/start scripts and nx start dependency

---

.github/workflows/pre-release.yaml

- In pre-release job, name step to `🔖 Github Pre-release (Tag + Pre-release)`
- In pre-release job, the step to create a pre-release had a misleading name
N/A

ci: 🚚 rename release step to pre-release

---

.commitlintrc.ts
.github/dependabot.yml

- configure initial dependabot setup to set the directory as `/`, allowing dependabot to detect project workspaces, check for security vulnerabilities, and update `pnpm-lock.yaml`.
See relevant sources:
- https://github.com/dependabot/dependabot-core/issues/10758
- https://github.com/dependabot/dependabot-core/issues/11135
- https://github.com/dependabot/dependabot-core/pull/11487
- dependabot isn't creating PRs for security updates to packages and `pnpm-lock.yaml`.
See dependabot PR in forked repo with dependabot config - It updates `pnpm-lock.yaml`
https://github.com/ktn1234/maiar-ai/pull/11

ci(dependabot): 🤖 setup initial dependabot config

---

.commitlintrc.ts
apps/client/package.json
pnpm-lock.yaml

- Remove devDep pkg `@types/react-virtualized-auto-sizer@1.0.8` since it is bogus and to get rid of pnpm warning
- `apps/client` pkg @types/react-virtualized-auto-sizer@1.0.8 is a stub definition
Run `pnpm i` and you will not get a warning for pkg `@types/react-virtualized-auto-sizer@1.0.8` being a stub definition anymore

chore(client): 🔥 remove devDep pkg @types/react-virtualized-auto-sizer@1.0.8

---

.github/workflows/ci.yaml
nx.json

This PR updates the CI workflows to use the `pull_request_target` event instead of `pull_request`. This change allows workflows to access repository secrets, such as `NX_CLOUD_ACCESS_TOKEN`, which are necessary for Nx Cloud integration during CI runs.
Previously, workflows triggered by `pull_request` from forks did not have access to repository secrets, leading to failures in Nx Cloud integration. Switching to `pull_request_target` ensures that workflows have the required permissions to access secrets and perform necessary actions in the base repository.
N/A

ci(ci,bug): 🐛 switch to pull_request_target for Nx Cloud integration

---

.github/dependabot.yml

- Set open-pull-requests-limit: 0 in Dependabot config to effectively block all normal version bump PRs.
- Prevents Dependabot from opening PRs for regular dependency updates.
- Ensures only security-related updates (via security advisories) will trigger PRs.
- Reduces noise and manual PR triage.
Source - https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
- Configure Dependabot to only create PRs for high severity security vulnerabilities in NPM dependencies.
Do not allow automatic version bumps for normal updates; manual updates will be handled separately.
Acceptance Criteria:
- No PRs for version bumps unless tied to a security advisory.
- Security PRs should be …

ci(dependabot): 🔧 assign open-pull-requests-limit to 0 to disable version updates for npm dependencies

---

.github/workflows/stale.yaml

- Added a new workflow for stale issues and PRs
- This workflow automatically marks issues and PRs as stale after 30 days of inactivity and closes them 7 days later if no activity occurs. It uses the [actions/stale](https://github.com/actions/stale) GitHub Action for labeling and closing stale items, with clear messages notifying users. This ensures better maintenance of the repo by automatically cleaning up inactive issues and PRs.
- Inactive issues and PRs often accumulate in repositories, leading to clutter and inefficiency. Without automated management, maintainers must manually track and close outdated items, which can be time-consuming and error-prone. This results in a less organized repository, where relevant tasks may get overlooked or buried under irrelevant, stale issues and …

ci: 👷 add stale issue/PR workflow for automatic marking and closure

---

.github/workflows/bounty.yaml
.github/workflows/rollback.yaml
.github/workflows/thank-you.yaml
package.json
pnpm-lock.yaml

🔙 Add Rollback Support to Release Workflow
This PR introduces a new GitHub Actions workflow that allows maintainers to rollback the main branch to a specific commit.  
It performs a hard reset, deletes any tags and associated GitHub Releases created after the target commit, and force-pushes the updated state.
Other changes:
- 📦 add devDep - @actions/github@6.0.0
- 👷 update bounty/thank-you workflow to use setup composite action
- No rollback strategy and mechanism to a certain commit hash
In your own fork, run the github action workflow `🔙 Rollback` and input the commit hash you want your default branch to rollback to. Observe that the HEAD is now at the commit hash and all of the tags/releases ahead of the commit hash are all deleted

ci(release): 👷 add rollback gha workflow to rollback to a specific commit hash

---

.github/workflows/pre-release.yaml
.github/workflows/publish.yaml

- nx release correctly derives next prerelease version based on conventional commits
- disable automatic npm publishing temporarily
- nx release was incorrectly derives next prerelease version based on conventional commits
Sources for fix:
- https://github.com/nrwl/nx/issues/22150
- https://github.com/nrwl/nx/discussions/23387#discussioncomment-11230516 - the comment with the actual fix 
Run the pre-release workflow in your fork after making a conventional commit and observe it will increment to correct next version based on conventional commits

fix(ci): 🐛 nx release correctly derives next prerelease version based on conventional commits

---

.github/workflows/ci.yaml

switched from `pull_request_target` to `pull_request` event in the CI workflow. this ensures the workflow runs using the forked PR code instead of the base repo code, preventing false positives and simplifying branch checkout logic.
n/a
1. open a PR from a forked repo
2. confirm that CI jobs use the correct commit (PR head, not base branch)
3. ensure build/lint/test jobs run against the expected code

fix(ci): 👷 use pull_request event to correctly checkout forked PR code

---

.github/workflows/ci.yaml

fixes incorrect code checkout in `pull_request_target` workflows. previously, only the `commit-lint` job correctly checked out the forked pr code. the `build-typecheck-lint` and `test` jobs were still checking out the base repo’s default branch, leading to inaccurate ci results. this change ensures *all* jobs use `github.event.pull_request.head` to fetch the correct branch from the fork.
n/a
* open a pr from a fork
* verify all jobs (`commit-lint`, `build-typecheck-lint`, `test`) checkout and run against the correct commit/branch from the fork
* check that the logs show the correct repo and commit sha from the pr head

fix(ci): 👷 checkout correct PR head from fork in all jobs
